version: '3.8'

services:
  database:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27018:27017" # Mongo Port auf 27018 ändern, um Konflikte zu vermeiden
    volumes:
      - mongodb-data:/data/db
      #- ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro # Das Skript wird beim Start ausgeführt
    environment:
        MONGO_INITDB_ROOT_USERNAME: express-bot
        MONGO_INITDB_ROOT_PASSWORD: 1VbfpRxD42kP

  backend:
    build:
      context: ./express-backend
      dockerfile: Dockerfile.backend
    container_name: backend-service
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app:rw
    environment:
      - MONGODB_URI=mongodb://express-bot:1VbfpRxD42kP@database:27017/email-bot-express
    depends_on:
      - database

  frontend:
    build:
      context: ./vue-frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend-service
    ports:
      - "8090:8080" # Change Frontend Port to 8090
    volumes:
      - ./frontend:/app:rw


volumes:
  mongodb-data:
    external: false
