FROM node:18

# Benutzer und Gruppe erstellen
RUN groupadd -r express-bot && useradd -r -g express-bot express-bot

# Arbeitsverzeichnis setzen
WORKDIR .

# Dateien kopieren
COPY package*.json ./

# Abhängigkeiten installieren
RUN npm install

# Quellcode kopieren
COPY . .

# Benutzer wechseln
USER express-bot

# Port exponieren
EXPOSE 3000

# Startbefehl
CMD ["npm", "start"]
